### ISSUE TITLE
Circuit Diagram of BQ25895 with Raspberry pi/Atmega328

### ISSUE THREAD

**Issue by aylashiv** [bernebeer/Charge-n-Boost#1]
Hi,

Could you please share the Schematic/Circuit diagram of the same.

**Comment by bernebeer** [comment]
Hi,

Yes, no problem. I'll put it up in a few hours, maybe at the end of the day.

Regards Gijs

**Comment by aylashiv** [comment]
Thanks

**Comment by bernebeer** [comment]
Hi, I have added a PDF file with the schematic. I do not have time to check at the moment but the code might not fully reflect some features. I remember some changes made to the RGB led. Hope this helps you out.

Regards,

Gijs

**Comment by aylashiv** [comment]
Hi
Thanks for sharing the schematic, I'll look into the circuit and will post the updates.

**Comment by aylashiv** [comment]
Hi Gijs,
We are also trying to integrate this Charger BQ25895 with SBC Raspberry pi, but we have trouble in setting the current limits and voltage over I2C using Raspberry pi. Do you have any Code with Raspberry pi, that would be a great help.

Thanks,
Shiva.

**Comment by bernebeer** [comment]
Hi Shiva,

Unfortunately I do not have raspberry pi code. If I remember correctly you can set an input current limit in one of the I2C registers. By default the charge IC will look for voltages on the data plus and minus pins sent by whatever the charge IC is connected to and set an input current limit as per battery charging protocol. The lower of which is actually set as input current limit. I can't remember if that can be overridden. What do you mean with setting voltage?

Regards,

Gijs

**Comment by aylashiv** [comment]
Hi Gijs,
Thanks for the information.
